---
title: "Course schedules"
output: 
 html_document:
  toc: false
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The module Macroecology and global change offers one lecture on *Macroecology* and two practical courses on *Macroecological analyses* and on *Species distribution modelling*, which are run in sequence.

#### Schedule for the winter term 2022/2023

```{r echo=F,include=FALSE}
library(kableExtra)
df <- data.frame(
  Week=c(
    '1 (Oct 17th - Oct 21th)',
    '2',
    '3',
    '4', 
    '5',
    '6', 
    '7', 
    '8',
    '9 (Dec 12th - Dec 16th)',
    '10 (Jan 2nd - Jan 6th)',
    '11',
    '12',
    '13',
    '14',
    '15 (Feb 6th - Feb 10th)'), 
  Exercise = c('Introduction. What is macroecology?',rep(c(''),14)),
  Lecture=c(
    'Global biodiversity patterns',
    '',
    'Limits to species distributions',
    'Drivers of biodiversity change',
    'Observed biodiversity change',
    'Species distribution models (SDM)',
    'SDM - model fitting and assessment',
    'SDM - pseudo-absence and background data',
    'SDM - algorithms and ensembles',
    'Modelling biodiversity dynamics I',
    'Modelling biodiversity dynamics II',
    'Functional and phylogenetic diversity',
    'Group work',
    'Q&A',
    'Presentations'),
  ColPractical=c(
    '(a) Macroecological analyses',
    '',
    '',
    '',
    '',
    '(b) Species distribution modelling',
    '',
    '', 
    '',
    '',
    'Group work',
    '',
    '',
    '',
    'Presentations'),
  Practical=c(
    '1. Spatial data in R',
    '2. Species richness gradients + 3. Species richness regression',
    '4. Species range maps',
    '5. Species threats', 
    '6. Biodiversity changes',
    '1. Species data + 2. Environmental data',
    '3. SDM I: simple model fitting + 4. SDM II: model assessment and prediction',
    '5. Pseudo-absence and background data', 
    '6. SDM III: algorithms',
    '7. SDM IV: ensembles',
    '',
    '',
    '',
    '',
    ''),
  Col=c(2,2,2,2,2,3,3,3,3,3,NA,NA,NA,NA,NA))
names(df)[2:5] <- c("Exercise/Helpdesk (Tuesdays)","Lecture (Thursdays)", "Seminar (Thursdays)","")
```

```{r results='asis', echo=FALSE}
df[,1:5] %>%
  knitr::kable(escape=F) %>%
  # kable_styling()
  kable_paper("hover", full_width = F) %>%
  column_spec(1, background = spec_color(1, end = 0.1, alpha=0.2, option='magma')) %>%
  column_spec(2, background = spec_color(df$Col, begin = 0.4, end=0.8, alpha=0.3, na_color="#E1E1E1"), bold=T) %>%
  column_spec(3, background = spec_color(1, begin=0.9, alpha=0.3), bold=T) %>%
  column_spec(4, background = spec_color(df$Col, begin = 0.4, end=0.8, alpha=0.3, na_color="#E1E1E1"), bold=T) %>%
  column_spec(5, background = spec_color(df$Col, begin = 0.4, end=0.8, alpha=0.3, na_color="#E1E1E1"))
```
